---

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: test-ag-nginx-tester
    docker_networks:
      - name: 'test-ag-nginx'
        ipam_config:
          - subnet: '192.168.12.0/24'
            gateway: '192.168.12.254'
    networks:
      - name: 'test-ag-nginx'
        ipv4_address: '192.168.12.1'
    groups: [grp_tester]
    docker_host: 'tcp://molecule-docker.local:2375'
    image: 'ansible0guy/molecule:debian-latest'
    tmpfs: ['/tmp', '/run', '/run/lock']
    privileged: true
    command: '/sbin/init'

provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - syntax
    - create
    - converge
    - verify
    - idempotence
    - check
    - destroy
